use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid;

/// Represents the general format of a an ingested log line.
///
/// We attempt to classify logs early so downstream
/// parsing and normalization can follow format-specific rules.
///
/// - `Plaintext` - unstructured, human-written logs.
/// - `JSON` - structured logs with key/value pairs.
/// - `Other(String)` - fallback for unknown formats.

#[derive(Debug, Clone, Serialize, Deserialize)]
enum LogType {
    Plaintext,
    JSON,
    Other(String), // TODO: Research additional formats
}

/// Represents severity level of a log event.
///
/// If a level can be reliably normalized, it will use one of the vartiants.
/// If not, `Other(String)` preserves the raw value as-is.
#[derive(Debug, Clone, Serialize, Deserialize)]
enum LogLevel {
    Trace,
    Debug,
    Info,
    Warn,
    Error,
    Fatal,
    Other(String), // fallback
}

/// A single ingested log line, initially normalized into a struct.
/// We will attempt to index, analyze, and correlate across services.
///
/// This is inntentionally flexible to support varied log formats across
/// distributed systems.

struct LogEvent {
    ///The detected format of the log line (plaintext, JSON, or user-defined).
    log_type: LogType,

    /// Optional normalized severity level.
    ///
    /// If it cannot be mapped to a known variant
    /// The value will be `Some(LogLevel::Other(_))`.
    log_level: Option<LogLevel>,

    /// Line number within the original source file.
    /// Useful for correlation diagnostics, stack traces, and multi-line messages.
    line_number: usize,

    /// Path or filename from which the log was ingested.
    ///
    /// Used for attribution and grouping.
    source_file: String,

    /// Service name (e.g. `auth service`, `payment-manager`, etc).
    ///
    /// May populate automatically during ingestion. User can also override or alias it for custom mapping.
    service: String,

    /// Normalized timestamp extracted from raw text, if parse succeeded.
    timestamp: Option<DateTime<Utc>>,

    /// Raw timestamp as it appeared in the source log.
    ///
    /// Kept for custom parsing or override normalization.
    raw_timestamp: Option<String>,

    /// Unique identifier for log line, generated by us.
    ///
    /// This should be stable across reloads and used for cross-service correlation
    ingest_id: uuid::Uuid,

    /// Arbitrary user-defined or auto-generated tags.
    ///
    /// Useful for grouping, filtering, or eventual ML classification.
    tags: Vec<String>,

    /// Original unmodified log text.
    raw_message: String,

    /// Normalized version of log message. May be relaced by a fully structured type once defined.
    message: Option<String>, // TODO: define normalized message struct
}
